[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "dggs-benchmarking"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
libc = { family = "glibc", version = "2.34" }

[tasks]

[dependencies]
jupyterlab = ">=4.4.5,<5"
jupyter-resource-usage = ">=1.1.1,<2"
jupyterlab_code_formatter = ">=3.0.2,<4"
black = "*"
isort = "*"
ruff = "*"
python = "3.12.*"
jedi-language-server = "*"
dask = ">=2025.7.0,<2026"
dask-labextension = ">=7.0.0,<8"
ipykernel = ">=6.30.1,<7"

[pypi-dependencies]
healpix-geo = "*"
xdggs = ">=0.2.2"

[environments]
ellipsoidal-healpix = ["ellipsoidal-healpix"]
regridding = ["regridding"]
eopf = ["eopf"]


[feature.ellipsoidal-healpix.dependencies]
pandas = "*"
matplotlib = "*"
seaborn = "*"
evcxr = "*"
fastparquet = ">=2024.11.0,<2025"

[feature.regridding.dependencies]
xarray = "*"
cfgrib = "*"
dask = "*"
xesmf = "*"
zarr = ">=3.1.2,<4"

[feature.eopf.dependencies]
xarray-eopf = "*"
xarray = "*"
pyproj = "*"
zarr = "<3"
pystac-client = "*"
matplotlib-base = "*"
